spring.application.name=Math-Gym

# Make session cookies Secure
server.servlet.session.cookie.secure=true

# Attempt to load DB credentials from environment variables or database.properties.
spring.config.import=optional:classpath:database.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
